version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    ignore:
      - "Microsoft.CodeAnalysis"
      - "Microsoft.CodeAnalysis.CSharp.Workspaces"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
